# These checks must pass before you may commit changes
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: pretty-format-json
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

# -   repo: https://github.com/psf/black
#     rev: 24.8.0
#     hooks:
#     -   id: black

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.6
    hooks:
    # Run the linter.
    # - id: ruff
    #   args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      args: [ --line-length=98 ]
