# When making changes to this file update requirements.txt also !!
# conda -v env update -n kimnaty --file environment.yml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - matplotlib
  - numpy
  - pandas
  - pip
  - pyarrow
  - requests
  - scipy
  - sh
  # Not on conda channels:
  - pip:
      - mausy5043-common
      # This won't install on anything other than Linux:
      - pylywsdxx
