# When making changes to this file update requirements.txt also !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: kimnaty

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  # imported deps
  - matplotlib=3.9.3
  - numpy=2.1.1
  - pandas=2.2.3
  - pyarrow=17.0.0
  - requests=2.32.3
  - sh=2.0.7

  # Not on conda channels:
  - pip:
      - gracefulkiller==0.4.7
      - mausy5043-common==1.8.2
      # This won't install on anything other than Linux:
      - pylywsdxx==2.2.2

  # dev deps
  - jupyterlab
  - pipdeptree
  - pre-commit
  - scipy
