# When making changes to this file update requirements.txt also !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: kimnaty

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13
  - pip

  # imported deps
  - matplotlib=3.10
  # already delivered by mausy5043-common, so no version here:
  - numpy
  - pandas
  # - pyarrow=19.0
  - requests=2.32
  - sh=2.2

  # Not on conda channels:
  - pip:
      - gracefulkiller~=0.4
      - mausy5043-common==2.4.5
      # This won't install on anything other than Linux:
      - pylywsdxx~=2.8

  # dev deps
  - jupyterlab
  - pandas-stubs
  - pipdeptree
  - pre-commit
  - scipy
