# When making changes to this file update requirements.txt also !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: kimnaty

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  # imported deps
  - matplotlib=3.10
  - numpy=2.2
  - pandas=2.2
  # already delivered by mausy5043-common:
  # - pyarrow=19.0
  - requests=2.32
  - sh=2.2

  # Not on conda channels:
  - pip:
      - gracefulkiller~=0.4
      - mausy5043-common==1.12.1
      # This won't install on anything other than Linux:
      - pylywsdxx~=2.6

  # dev deps
  - jupyterlab
  - pandas-stubs
  - pipdeptree
  - pre-commit
  - scipy
