# When making changes to this file update requirements.txt also !!

name: kimnaty

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - requests
  - scipy
  # Not on conda channels:
  - pip:
      - mausy5043-common
      # This won't install on anything other than Linux:
      # - pylywsdxx
