# When making changes to this file update requirements.txt also !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: kimnaty

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pre-commit
  - pyarrow
  - requests
  - scipy
  - sh
  # Not on conda channels:
  - pip:
      - gracefulkiller
      - mausy5043-common
      # This won't install on anything other than Linux:
      - pylywsdxx
