#!/usr/bin/env bash

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)

pushd "${HERE}" >/dev/null || exit 1

# shellcheck disable=SC1091
source ./bin/constants.sh

# check commandline parameters
for i in "$@"; do
    case $i in
    -i | --install)
        install_kimnaty "${HERE}"
        ;;
    -u | --uninstall)
        unstall_kimnaty
        ;;
    -s | --stop)
        stop_kimnaty
        ;;
    -g | --go)
        start_kimnaty "${HERE}" "-nograph"
        ;;
    -b | --boot)
        boot_kimnaty
        ;;
    -r | --restart)
        restart_kimnaty "${HERE}" 0
        ;;
    --systemd )
        restart_kimnaty "${HERE}" 1
        ;;
    --graph)
        graph_kimnaty "${HERE}"
        ;;
    --update)
        update_kimnaty
        ;;
    *)
        # unknown option
        echo "** Unknown option **"
        echo
        echo "Syntax:"
        echo "kimnaty [-i|--install] [-g|--go] [-r|--restart|--graph]  [-s|--stop] [-u|--uninstall]"
        echo
        exit 1
        ;;
    esac
done

popd >/dev/null || exit 1
